### ISSUE TITLE
Error at startup - EACCES: permission denied

### ISSUE THREAD

**Issue by franckgaga** [chrisknepper/android-messages-desktop#149] opened 2019-04-02 14:22 UTC
Hi,

I'm running on Linux Mint 19.1 Cinnamon 64 bit (linux kernel 4.15.0-46-generic)

I have the following error message at the start up of the app :

![image](https://user-images.githubusercontent.com/34136215/55409941-fa70d300-5530-11e9-92c4-2949d991ed18.png)

It's worth mentioning that the app is still fully usable when i click "OK"

Thanks !

**Comment by ajivoin** [comment] 2019-04-03 14:29
I was getting that error after updating to 0.9.1. I had to completely re-install for it to go away.

**Comment by franckgaga** [comment] 2019-04-03 14:36
I've just tried full re-installation of 0.9.1 and it did not solves the issue...

**Comment by chrisknepper** [comment] 2019-04-06 01:31
I checked this out today in Ubuntu and I can confirm it happening. It looks like this is happening because in Linux, the app only has the permission to write new files and overwrite files in that folder, not delete files. I can fix this but it will take a little time--in the meantime you may be able to work around this by:

1. Going to the folder where the app is installed and deleting all the files inside the resources/dictionaries folder
2. Exiting the program, running it once as root, then running it normally

**Comment by jjgalvez** [comment] 2019-04-06 01:41
just updated to 1.0.0 and no errors

**Comment by franckgaga** [comment] 2019-04-08 20:25
yep, 1.0.0 solve the problem, thanks for the support !

**Comment by chrisknepper** [comment] 2019-09-04 23:57
This should now be fixed in the latest release, v3.0.0

**Closed by chrisknepper** 2019-09-04 23:57 UTC
